package com.example.projekt_proba2

import android.widget.RadioGroup
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavHostController
import com.example.projekt_proba2.data.Item
import com.example.projekt_proba2.data.ItemViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun settings(viewModel: ItemViewModel,  navController: NavHostController)
{

    var Goal by remember {
        mutableStateOf("")
    }

    var isOptionSelected by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {


        OutlinedTextField(value = Goal,
            onValueChange = { Goal = it },
            label = { Text("Goal value") },
            keyboardOptions = KeyboardOptions.Default.copy(
                keyboardType = KeyboardType.Number
            ),
        )


            Row(
                modifier = Modifier.padding(16.dp),
                horizontalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                RadioButton(
                    selected = isOptionSelected,
                    onClick = {
                        isOptionSelected = true
                        // Handle the selected option
                    }
                )
                Text("Minimum Calorie")

                RadioButton(
                    selected = !isOptionSelected,
                    onClick = {
                        isOptionSelected = false
                        // Handle the selected option
                    }
                )
                Text("Maximum Calorie")
            }

        Button(onClick = {

            var newItem = Item(
                id = 1, // Auto-generated by Room or set to 1 we will see
                date = 2137, //set value to know where item is
                brekafast = Goal.toInt(), //goal
                lunch = if(isOptionSelected){1}else{0},//0 is max calorie, 1 is min calorie
                dinner =0 //unused
            )
            if(viewModel.checkIfItemExists(2137))
            {
                viewModel.updateItemDetails(newItem)

            }
            else
            {
                viewModel.addItem(newItem)
            }

            navController.navigate("calendar")

        }) {
            Text(text = "confirm",fontSize = 16.sp)
        }

        Button(onClick = {
            viewModel.deleteAll()

            //adding default settings
            var newItem = Item(
                id = 1, // id 1 set as default value for settings
                date = 2137, //set value to know where item is
                brekafast = 2000, //goal
                lunch = 1,//1 is max calorie, 0 is min calorie
                dinner =0 //unused
            )
            viewModel.addItem(newItem)



            navController.navigate("calendar")
        }) {
            Text(text = "delete data",fontSize = 16.sp)
        }



    }
}


