package com.example.projekt

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier

import com.example.projekt.data.Item

import java.util.Date


@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun todaysMealScreen(

)
{







    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {

            var Brekafast by remember { mutableStateOf("") }
            var Lunch by remember { mutableStateOf("") }
            var Dinner by remember { mutableStateOf("") }


            OutlinedTextField(value = Brekafast,
                onValueChange = { Brekafast = it },
                label = { Text("Brekfast") }
            )
            OutlinedTextField(value = Lunch,
                onValueChange = { Lunch = it },
                label = { Text("Lunch") }
            )
            OutlinedTextField(value = Dinner,
                onValueChange = { Dinner = it },
                label = { Text("Dinner") }
            )
            

            Button(onClick = {
                val newItem = Item(
                    id = 0, // Auto-generated by Room
                    date = Date(), // You may want to set the actual date here
                    brekafast = Brekafast.toInt(),
                    lunch = Lunch.toInt(),
                    dinner = Dinner.toInt()
                )


                //viewModel.addItem(newItem)
            }
            ) {
                Text(text = "submit")
            }

    }
}